spring.application.name=gamestore

# Configurar o banco de dados

spring.datasource.url=jdbc:postgresql://dpg-d6tvgnia214c73cr3qq0-a.virginia-postgres.render.com/db_deploy_gs_thayssam
spring.datasource.username=db_deploy_gs_thayssam_user
spring.datasource.password=${DB_PASSWORD}
# OBS: Nunca colocar senhas em documentos que vão para o github

# Configurações do jpa - hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
